name: claes
favicon: null
layout_spectrum: 0.3554083008784801
typography_spectrum: 0.5060409512370825
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7345275662373751
  lightness: 0.88487313920632
  saturation: 0.4788211619015783
  rhythmicContrast: 0.7392265084199607
purpose: []
